AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 7.0.4.3
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"

# Missing top-level documentation comment for...
Documentation:
  Enabled: false

# Missing frozen string literal comment.
Style/FrozenStringLiteralComment:
  Enabled: false
